/** Figma-exported assets under /public/assets/home */
export const homeAssets = {
  logo: "/assets/home/ck-logo.svg",
  missionLogo: "/assets/home/mission-logo.svg",
  arrowCta: "/assets/home/arrow-cta.svg",
  arrowCtaBlue: "/assets/home/arrow-cta-blue.svg",
  bgColors: "/assets/home/bg-colors.png",
  orbitRing: "/assets/home/orbit-ring.svg",
  orbitInner: "/assets/home/orbit-inner.svg",
  orbitDotLarge: "/assets/home/orbit-dot-large.svg",
  orbitDotSmall: "/assets/home/orbit-dot-small.svg",
  chevronDown: "/assets/home/chevron-down.svg",
  searchIcon: "/assets/home/search-icon.svg",
  gcpLogo: "/assets/home/gcp-logo.png",
  awsBadge: "/assets/home/aws-partner-badge.png",
  azureLogo: "/assets/home/azure-partner-badge.png",
  soc2Iso: "/assets/home/soc2-partner-badge.png",
  partnerBadges: "/assets/home/partner-badges.png",
  platformDashboard: "/assets/home/platform-dashboard.svg",
  statExpertise: "/assets/home/stat-expertise.svg",
  statSavings: "/assets/home/stat-savings.svg",
  statCertified: "/assets/home/stat-certified.svg",
  statCustomers: "/assets/home/stat-customers.svg",
  statementBg: "/assets/home/statement-bg.png",
  /** Figma 8294:8755 — full card background (1440×240) */
  statementCardBg: "/assets/home/statement-card-bg.png",
  testimonialSteven: "/assets/home/testimonial-steven.svg",
  playIcon: "/assets/home/play-icon.svg",
  quoteMark: "/assets/home/quote-mark.svg",
  linkArrow: "/assets/home/link-arrow.svg",
  capabilitiesCenterLogo: "/assets/home/capabilities-center-logo.svg",
  icons: {
    kubernetes: "/assets/home/icon-kubernetes.svg",
    multicloud: "/assets/home/icon-multicloud.svg",
    commit: "/assets/home/icon-commit.svg",
    ai: "/assets/home/icon-ai.svg",
    usage: "/assets/home/icon-usage.svg",
    visibility: "/assets/home/icon-visibility.svg",
    support: "/assets/home/icon-support.svg",
  },
} as const;
