import { homeAssets } from "@/config/home-assets";

/** Desktop chip positions from Figma node 8286:8440 (nested pointer groups) */
export const heroServices = [
  {
    label: "Usage\nOptimization",
    icon: homeAssets.icons.usage,
    side: "left" as const,
    left: 51,
    top: 210,
    iconWidth: 30,
    iconHeight: 30,
    revealIndex: 1,
  },
  {
    label: "Cloud Cost\nVisibility & Analytics",
    icon: homeAssets.icons.visibility,
    side: "left" as const,
    left: 110,
    top: 370,
    iconWidth: 30,
    iconHeight: 30,
    revealIndex: 5,
  },
  {
    label: "24 x 7 Unlimited\nCloud Support",
    icon: homeAssets.icons.support,
    side: "left" as const,
    left: 355,
    top: 506,
    iconWidth: 20,
    iconHeight: 22.223,
    iconBgRadius: "rounded-[6px]" as const,
    revealIndex: 7,
  },
  {
    label: "Multi-Cloud\nGovernance",
    icon: homeAssets.icons.multicloud,
    side: "right" as const,
    left: 315,
    top: 0,
    iconWidth: 21,
    iconHeight: 22,
    iconBgRadius: "rounded-[6px]" as const,
    revealIndex: 2,
  },
  {
    label: "Kubernetes\nCost Management",
    icon: homeAssets.icons.kubernetes,
    side: "right" as const,
    left: 265,
    top: 237,
    iconWidth: 25.607,
    iconHeight: 24.7,
    revealIndex: 3,
  },
  {
    label: "Rate & Commitment\nOptimization",
    icon: homeAssets.icons.commit,
    side: "right" as const,
    left: 0,
    top: 338,
    iconWidth: 28.607,
    iconHeight: 22.138,
    revealIndex: 4,
  },
  {
    label: "FinOps for AI",
    icon: homeAssets.icons.ai,
    side: "right" as const,
    left: 75,
    top: 483,
    iconWidth: 22.696,
    iconHeight: 22.694,
    revealIndex: 6,
  },
];

export const statsCards = [
  {
    value: "15",
    suffix: "+",
    label: "Years of\nCloud Expertise",
    bg: "#e2fdff",
    illustration: homeAssets.statExpertise,
    illustrationWidth: "134px",
    illustrationHeight: "118px",
    illustrationLeft: "177px",
    illustrationTop: "188.7px",
    illustrationInsetBottom: "-19.3%",
    illustrationOpacity: 1,
  },
  {
    value: "20",
    suffix: "%",
    label: "Average Cloud Savings Delivered",
    bg: "#fff4e0",
    illustration: homeAssets.statSavings,
    illustrationWidth: "134px",
    illustrationHeight: "131px",
    illustrationLeft: "175px",
    illustrationTop: "200.7px",
    illustrationOpacity: 0.12,
  },
  {
    value: "150",
    suffix: "+",
    label: "Certified Engineers & Architects",
    bg: "#e9eeff",
    illustration: homeAssets.statCertified,
    illustrationWidth: "103.804px",
    illustrationHeight: "142.983px",
    illustrationLeft: "203.23px",
    illustrationTop: "188px",
    illustrationOpacity: 1,
  },
  {
    value: "400",
    suffix: "+",
    label: "Global\nCustomers",
    bg: "#ffecf0",
    illustration: homeAssets.statCustomers,
    illustrationWidth: "134.689px",
    illustrationHeight: "158.358px",
    illustrationLeft: "170.57px",
    illustrationTop: "183.27px",
    illustrationOpacity: 1,
  },
];
